version: '3.3'

services:
  db-node-1:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sql_test
      MYSQL_USER: test
      MYSQL_PASSWORD: pzjqUkMnc7vfNHET
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - shop-network
    ports:
      - 3360:3306
    volumes:
      - db-node-1-data:/var/lib/mysql

  db-node-2:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sql_test
      MYSQL_USER: test
      MYSQL_PASSWORD: pzjqUkMnc7vfNHET
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - shop-network
    ports:
      - 3361:3306
    volumes:
      - db-node-2-data:/var/lib/mysql

  db-node-3:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sql_test
      MYSQL_USER: test
      MYSQL_PASSWORD: pzjqUkMnc7vfNHET
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - shop-network
    ports:
      - 3362:3306
    volumes:
      - db-node-3-data:/var/lib/mysql
      
  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    depends_on:
      - "db-node-1"
      - "db-node-2"
      - "db-node-3"
    command: >
      --initial
    volumes:
      - proxysql-data:/var/lib/proxysql
    networks:
      - shop-network
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"
  
  ignite-node-1:
    image: applem1support/ignite:2.12.0
    container_name: ignite-node-1
    # cpus: "0.4"
    environment:
        - CONFIG_URI=file:///home/user/4nodes/config/docker-ignite.xml
        - JVM_OPTS=-Xms512m -Xmx512m -server -XX:ActiveProcessorCount=1 -XX:+UseG1GC -XX:MaxPermSize=256m -XX:+DisableExplicitGC -DIGNITE_PERFORMANCE_SUGGESTIONS_DISABLED=true -Djava.net.preferIPv4Stack=true
    expose:
        - "47500-47509"
    networks:
        - shop-network
    volumes:
        - /home/alidar/mipt_architecture/docker/ignite_config:/home/user/4nodes/config
    ports:
        - "10800:10800"
  
  zookeeper:
      image: zookeeper
      container_name: zookeeper
      environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
          ZOOKEEPER_INIT_LIMIT: 5
  kafka-node-1:
      image: wurstmeister/kafka
      container_name: kafka-node-1
      depends_on:
          - zookeeper
      ports:
          - "2181:2181"
          - "9092:9092"
      environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_HOST_NAME: localhost
          ADVERTISED_PORT: 9092
          ADVERTISED_HOST_NAME: localhost
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  db-node-1-data:
  db-node-2-data:
  db-node-3-data:
  proxysql-data:

networks:
  shop-network:
    driver: "bridge"
    # external: false